### PR TITLE
Fix to add 2021-22 tbo

### LINKED ISSUE #47: Add more annual therapy-based outcomes archives and PROMs datasets
We currently have archives for three annual reporting periods of the therapy-based outcomes reports and should start adding more. The annual data files are linked from this page [NHS Talking Therapies, for anxiety and depression, Annual reports](https://digital.nhs.uk/data-and-information/publications/statistical/nhs-talking-therapies-for-anxiety-and-depression-annual-reports/), usually displayed as a ZIP file named `TBO Data Files`.

Before starting to work on this ticket we should decide how many new periods we want to add, I would suggest we start with one or two? This ticket involves:

- [x] **Adding new zip archives** to: https://github.com/bennettoxford/nhstt/blob/8b4c9d5a6976698a388f5dce986a82bf9b2570ee/inst/config/raw_annual_data_config.yml#L30-L39
- [x] **Updating the schema** with column names from the new archive by running `just update-schemas`. This will update the file [`inst/schemas/annual_tbo_schemas.csv`](https://github.com/bennettoxford/nhstt/blob/main/inst/schemas/annual_tbo_schemas.csv).
- [x] **Compare column names for Table 4** using [`compare_schemas()`](https://github.com/bennettoxford/nhstt/blob/3d78db5aa7d0c09fb8198302e9524e62bff25249/R/dev-utils.R#L309-L328) function to check if all column names are still identical across reporting periods. If not, we will need to rename columns in [`inst/config/tidy_annual_data_config.yml`](https://github.com/bennettoxford/nhstt/blob/3d78db5aa7d0c09fb8198302e9524e62bff25249/inst/config/tidy_annual_data_config.yml)
- [x] **Add the dataset files** for Table 4 to `proms_annual`: https://github.com/bennettoxford/nhstt/blob/8b4c9d5a6976698a388f5dce986a82bf9b2570ee/inst/config/raw_annual_data_config.yml#L77-L83
- [x] Verify that `get_proms_annual()` works with the new reporting periods
- [x] Add unit tests, including fixtures (see https://github.com/bennettoxford/nhstt/pull/46/commits/4fa78a074bdfeeabb67eff82563dee7d0fb55f8e). We probably dont need another integration test, as we're currently doing this in a very minimal way and the one we added in https://github.com/bennettoxford/nhstt/pull/46/commits/67be658d363ba7988ab8f9690e7f2ab132d092f4 tests the full pipleine.
- [x] Make sure that code is well formatted, all tests are passing, and package can be build, see the suggested development workflow [here](https://github.com/bennettoxford/nhstt/blob/main/DEVELOPERS.md#development-workflow)

### PR DESCRIPTION
**Pull request by Lola-Audrey**
Closes #47 

This also add a new developer function `create_raw_fixture` that will make it easier to create fixtures for testing, e.g., for this PR I ran:

```
> nhstt:::create_raw_fixture("proms_annual", "2021-22", "annual")
✔ Created fixture: tests/testthat/fixtures/schemas/annual/proms_annual/raw/2021-22.csv (5 rows, 33 cols)
> nhstt:::create_raw_fixture("therapy_position_annual", "2021-22", "annual")
✔ Created fixture: tests/testthat/fixtures/schemas/annual/therapy_position_annual/raw/2021-22.csv (5 rows, 5 cols)
```

### CODE REVIEW

**Comment by milanwiedemann** [comment]
I found an argument that helps us with the different behaviours of the zip archives, https://stat.ethz.ch/R-manual/R-devel/library/utils/html/unzip.html. We can use this to simplify the previous idea:

> `junkpaths`: If TRUE, use only the basename of the stored filepath when extracting. The equivalent of unzip -j.

**Comment by milanwiedemann** [comment]
The 2021-22 TBO archive has files nested in a subdirectory (`ther-based-outcomes-2122/Table1.csv`), while 2022-23+ archives have files at root level (`Table1.csv`).                                                                                   
                                                                                                                                                             
By adding `junkpaths = TRUE` to unzip(), all files are extracted flat to the temp directory regardless of their internal archive structure. Now we can match on just the filename:                                                                                                                                      
                                                                                                                                                             
```
> nhstt:::list_archive_files(archive_name = "annual_tbo", periods = c("2021-22", "2022-23"))                                                               
$`2021-22`                                                                                                                                                 
[1] "Table1.csv"              "Table2.csv"              ...                                                                                                
                                                                                                                                                             
$`2022-23`                                                                                                                                                 
[1] "Table1.csv"              "Table2.csv"              ...     
```

File: R/raw.R [hunk 1]
```diff
@@ -255,6 +255,13 @@ extract_csv_from_archive <- function(archive_path, csv_pattern) {
         cli_abort("No CSV files found in raw data file")
       }
 
+      normalized_temp_dir <- normalizePath(temp_dir, winslash = "/", mustWork = TRUE)
+      normalized_csv_files <- normalizePath(csv_files, winslash = "/", mustWork = TRUE)
+      relative_paths <- sub(paste0("^", normalized_temp_dir, "/"), "", normalized_csv_files)
+
+      matches <- grepl(csv_pattern, basename(csv_files), ignore.case = TRUE) |. grepl(csv_pattern, relative_paths, ignore.case = TRUE)
```
Comment (milanwiedemann) [inline R/raw.R]: I think the only reason this didnt work before was the `.` after the `|`, which I assumed was a typo?
